"""
Thingsboard Client
Holds the constants used in the Thingsboard client.
"""

class Constants:
    """
    Constants for Thingsboard Client.
    """
    state = "s"
    ts = "ts"
    CONFIG_KEY = "configuration"
    CONFIG_CHECKSUM_KEY = "configuration.checksum"
    ENGINE_CONFIG_KEY = "configuration.engine"
    LOCATION_CONSENT_ENABLED_KEY = "locationConsentEnabled"
    TELEMETRY_CONSENT_ENABLED_KEY = "telemetryConsentEnabled"
    GEOFENCE_ENABLED_KEY = "geofenceEnabled"
    GEOFENCE_KEY = "geofence"
    TB_ACCESS_TOKEN_PATH = "/data/tb_access_token"
    SN_PATH = "/data/factory/serial_number"
    TB_CONSENTS_PATH = "/data/tb_consents/"
    BLE_SECRET_AUTH_KEY_PATH = "/data/ble_secret.json"
    CURRENT_LOCATION_FILE = "/data/current_location.json"
    center = "center"
    radius = "radius"
    longitude = "longitude"
    latitude = "latitude"
    sp = "sp"
    LOCATION = "LOCATION"
    SERIAL_PORT = "SERIAL_PORT"
    POSITION = "position"
    LAT = "lat"
    LONG = "long"
    THINGSBOARD_SETTINGS_KEY = "ThingsboardSettings"
    GNSS = "GNSS"
    CLOUD_PUBLISH_INTERVAL = "CLOUD_PUBLISH_INTERVAL"
    FLUSH_MAX_UPDATES = "FLUSH_MAX_UPDATES"
    GPSD_UPDATE_INTERVAL = "GPSD_UPDATE_INTERVAL"
    GNSS_UPDATE_INTERVAL = "GNSS_UPDATE_INTERVAL"
    GPSD_STATIONARY_ERR_MARGIN = "GPSD_STATIONARY_ERR_MARGIN"
    GPSD_MOVING_ERR_MARGIN = "GPSD_MOVING_ERR_MARGIN"
    OUT_OF_GEOFENCE_COUNT = "OUT_OF_GEOFENCE_COUNT"
    DISTANCE = "DISTANCE"
    SPEED = "SPEED"
    MIN_CHANGE = "MIN_CHANGE"
    trips = "trips"
    n2k = "n2k"
